name: GitHub Actions Maven build example
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout the main branch
        uses: actions/checkout@v3
        
      - name: Step 2 - Setting up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Step 3 - Have GitHub actions build the Maven Project
        run: mvn -B package --file pom.xml

      - name: Step 4 - List the current directory
        run: ls -a

      - name: Step 5 - What is in the target folder?
        run: |
          cd target
          ls -a
          
